---
- name: MySQL Database Backup
  hosts: database
  become: true
  tasks:
    - name: Copy backup script to remote
      copy:
        src: scripts/db_backup.sh
        dest: /tmp/db_backup.sh
        mode: '0755'

    - name: Execute backup script
      command: /tmp/db_backup.sh
